# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import khronos_pb2 as khronos__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in khronos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScheduleServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSchedule = channel.unary_unary(
                '/khronos.ScheduleService/CreateSchedule',
                request_serializer=khronos__pb2.CreateScheduleRequest.SerializeToString,
                response_deserializer=khronos__pb2.CreateScheduleResponse.FromString,
                _registered_method=True)
        self.UpdateSchedule = channel.unary_unary(
                '/khronos.ScheduleService/UpdateSchedule',
                request_serializer=khronos__pb2.UpdateScheduleRequest.SerializeToString,
                response_deserializer=khronos__pb2.UpdateScheduleResponse.FromString,
                _registered_method=True)
        self.DeleteSchedule = channel.unary_unary(
                '/khronos.ScheduleService/DeleteSchedule',
                request_serializer=khronos__pb2.DeleteScheduleRequest.SerializeToString,
                response_deserializer=khronos__pb2.DeleteScheduleResponse.FromString,
                _registered_method=True)
        self.ListSchedules = channel.unary_unary(
                '/khronos.ScheduleService/ListSchedules',
                request_serializer=khronos__pb2.ListSchedulesRequest.SerializeToString,
                response_deserializer=khronos__pb2.ListSchedulesResponse.FromString,
                _registered_method=True)


class ScheduleServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScheduleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchedule,
                    request_deserializer=khronos__pb2.CreateScheduleRequest.FromString,
                    response_serializer=khronos__pb2.CreateScheduleResponse.SerializeToString,
            ),
            'UpdateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSchedule,
                    request_deserializer=khronos__pb2.UpdateScheduleRequest.FromString,
                    response_serializer=khronos__pb2.UpdateScheduleResponse.SerializeToString,
            ),
            'DeleteSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchedule,
                    request_deserializer=khronos__pb2.DeleteScheduleRequest.FromString,
                    response_serializer=khronos__pb2.DeleteScheduleResponse.SerializeToString,
            ),
            'ListSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchedules,
                    request_deserializer=khronos__pb2.ListSchedulesRequest.FromString,
                    response_serializer=khronos__pb2.ListSchedulesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'khronos.ScheduleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('khronos.ScheduleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScheduleService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/khronos.ScheduleService/CreateSchedule',
            khronos__pb2.CreateScheduleRequest.SerializeToString,
            khronos__pb2.CreateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/khronos.ScheduleService/UpdateSchedule',
            khronos__pb2.UpdateScheduleRequest.SerializeToString,
            khronos__pb2.UpdateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/khronos.ScheduleService/DeleteSchedule',
            khronos__pb2.DeleteScheduleRequest.SerializeToString,
            khronos__pb2.DeleteScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/khronos.ScheduleService/ListSchedules',
            khronos__pb2.ListSchedulesRequest.SerializeToString,
            khronos__pb2.ListSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkflowServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartWorkflow = channel.unary_unary(
                '/khronos.WorkflowService/StartWorkflow',
                request_serializer=khronos__pb2.StartWorkflowRequest.SerializeToString,
                response_deserializer=khronos__pb2.StartWorkflowResponse.FromString,
                _registered_method=True)
        self.GetWorkflow = channel.unary_unary(
                '/khronos.WorkflowService/GetWorkflow',
                request_serializer=khronos__pb2.GetWorkflowRequest.SerializeToString,
                response_deserializer=khronos__pb2.GetWorkflowResponse.FromString,
                _registered_method=True)
        self.ListWorkflows = channel.unary_unary(
                '/khronos.WorkflowService/ListWorkflows',
                request_serializer=khronos__pb2.ListWorkflowsRequest.SerializeToString,
                response_deserializer=khronos__pb2.ListWorkflowsResponse.FromString,
                _registered_method=True)
        self.CancelWorkflow = channel.unary_unary(
                '/khronos.WorkflowService/CancelWorkflow',
                request_serializer=khronos__pb2.CancelWorkflowRequest.SerializeToString,
                response_deserializer=khronos__pb2.CancelWorkflowResponse.FromString,
                _registered_method=True)


class WorkflowServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StartWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.StartWorkflow,
                    request_deserializer=khronos__pb2.StartWorkflowRequest.FromString,
                    response_serializer=khronos__pb2.StartWorkflowResponse.SerializeToString,
            ),
            'GetWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflow,
                    request_deserializer=khronos__pb2.GetWorkflowRequest.FromString,
                    response_serializer=khronos__pb2.GetWorkflowResponse.SerializeToString,
            ),
            'ListWorkflows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkflows,
                    request_deserializer=khronos__pb2.ListWorkflowsRequest.FromString,
                    response_serializer=khronos__pb2.ListWorkflowsResponse.SerializeToString,
            ),
            'CancelWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelWorkflow,
                    request_deserializer=khronos__pb2.CancelWorkflowRequest.FromString,
                    response_serializer=khronos__pb2.CancelWorkflowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'khronos.WorkflowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('khronos.WorkflowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkflowService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/khronos.WorkflowService/StartWorkflow',
            khronos__pb2.StartWorkflowRequest.SerializeToString,
            khronos__pb2.StartWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/khronos.WorkflowService/GetWorkflow',
            khronos__pb2.GetWorkflowRequest.SerializeToString,
            khronos__pb2.GetWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/khronos.WorkflowService/ListWorkflows',
            khronos__pb2.ListWorkflowsRequest.SerializeToString,
            khronos__pb2.ListWorkflowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/khronos.WorkflowService/CancelWorkflow',
            khronos__pb2.CancelWorkflowRequest.SerializeToString,
            khronos__pb2.CancelWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PollActivity = channel.unary_unary(
                '/khronos.WorkerService/PollActivity',
                request_serializer=khronos__pb2.PollActivityRequest.SerializeToString,
                response_deserializer=khronos__pb2.PollActivityResponse.FromString,
                _registered_method=True)
        self.ReportActivityResult = channel.unary_unary(
                '/khronos.WorkerService/ReportActivityResult',
                request_serializer=khronos__pb2.ReportActivityResultRequest.SerializeToString,
                response_deserializer=khronos__pb2.ReportActivityResultResponse.FromString,
                _registered_method=True)
        self.ReportActivityFailure = channel.unary_unary(
                '/khronos.WorkerService/ReportActivityFailure',
                request_serializer=khronos__pb2.ReportActivityFailureRequest.SerializeToString,
                response_deserializer=khronos__pb2.ReportActivityFailureResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/khronos.WorkerService/Heartbeat',
                request_serializer=khronos__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=khronos__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PollActivity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportActivityResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportActivityFailure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PollActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.PollActivity,
                    request_deserializer=khronos__pb2.PollActivityRequest.FromString,
                    response_serializer=khronos__pb2.PollActivityResponse.SerializeToString,
            ),
            'ReportActivityResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportActivityResult,
                    request_deserializer=khronos__pb2.ReportActivityResultRequest.FromString,
                    response_serializer=khronos__pb2.ReportActivityResultResponse.SerializeToString,
            ),
            'ReportActivityFailure': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportActivityFailure,
                    request_deserializer=khronos__pb2.ReportActivityFailureRequest.FromString,
                    response_serializer=khronos__pb2.ReportActivityFailureResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=khronos__pb2.HeartbeatRequest.FromString,
                    response_serializer=khronos__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'khronos.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('khronos.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PollActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/khronos.WorkerService/PollActivity',
            khronos__pb2.PollActivityRequest.SerializeToString,
            khronos__pb2.PollActivityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportActivityResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/khronos.WorkerService/ReportActivityResult',
            khronos__pb2.ReportActivityResultRequest.SerializeToString,
            khronos__pb2.ReportActivityResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportActivityFailure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/khronos.WorkerService/ReportActivityFailure',
            khronos__pb2.ReportActivityFailureRequest.SerializeToString,
            khronos__pb2.ReportActivityFailureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/khronos.WorkerService/Heartbeat',
            khronos__pb2.HeartbeatRequest.SerializeToString,
            khronos__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
